name: Deploy PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist_credentials: false
          fetch_depth: 0
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
          working_directory: latex/src
      - name: Copy
        run: |
          mkdir out
          mv ./latex/src/thesis.pdf ./latex/pdf/thesis.pdf
          git add ./latex/pdf
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
